export { default as Home } from './Home'
export { default as Discover } from './Discover'
export { default as Messages } from './Messages'
export { default as Notification } from './Notification'
export { default as Profile } from './account/Profile'
export { default as Settings } from './account/Settings'
export { default as Logout } from './account/Logout'