export { default as Nav } from './Nav'
export { default as Footer } from './Footer'
export { default as Photo } from './Photo'
export { default as Photos } from './Photos'
export { default as Comment } from './Comment'
export { default as Comments } from './Comments'
export { default as Users } from './Users'
export { default as User } from './User'